CREATE USER 'repl_2'@'%' IDENTIFIED BY 'pass';
GRANT REPLICATION SLAVE ON *.* TO 'repl_2'@'%';
CHANGE REPLICATION SOURCE TO
SOURCE_HOST='compose_mysql_master1',
SOURCE_USER='repl_2',
SOURCE_PASSWORD='pass',
SOURCE_SSL=1;
START REPLICA;