Vagrant.configure("2") do |config|

  config.vm.define "ubuntu_host1" do |ubuntu_host1|
    ubuntu_host1.vm.box = "ubuntu/focal64"
    ubuntu_host1.vm.hostname = 'ubuntu-host1'
    ubuntu_host1.vm.box_url = "ubuntu/focal64"

    ubuntu_host1.vm.network :public_network, bridge: "enp5s0", ip: "192.168.0.101"

    ubuntu_host1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4056]
      v.customize ["modifyvm", :id, "--name", "ubuntu-host1"]
    end
  end
  config.vm.define "ubuntu_host2" do |ubuntu_host2|
    ubuntu_host2.vm.box = "ubuntu/focal64"
    ubuntu_host2.vm.hostname = 'ubuntu-host2'
    ubuntu_host2.vm.box_url = "ubuntu/focal64"

    ubuntu_host2.vm.network :public_network, bridge: "enp5s0", ip: "192.168.0.102"

    ubuntu_host2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4056]
      v.customize ["modifyvm", :id, "--name", "ubuntu-host2"]
    end
  end
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    # install java runtime environment
    apt-get install -y default-jre
    # install docker
    apt-get install -y docker.io
    usermod -a -G docker vagrant
  SHELL
end