Vagrant.configure("2") do |config|

  config.vm.define "ubuntu_host1" do |ubuntu_host1|
    ubuntu_host1.vm.box = "ubuntu/focal64"
    ubuntu_host1.vm.hostname = 'ubuntu-host1'
    ubuntu_host1.vm.box_url = "ubuntu/focal64"

    ubuntu_host1.vm.network :public_network, bridge: "enp5s0", ip: "192.168.0.101"

    ubuntu_host1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4056]
      v.customize ["modifyvm", :id, "--name", "ubuntu-host1"]
    end
  end
  config.vm.define "ubuntu_host2" do |ubuntu_host2|
    ubuntu_host2.vm.box = "ubuntu/focal64"
    ubuntu_host2.vm.hostname = 'ubuntu-host2'
    ubuntu_host2.vm.box_url = "ubuntu/focal64"

    ubuntu_host2.vm.network :public_network, bridge: "enp5s0", ip: "192.168.0.102"

    ubuntu_host2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 4056]
      v.customize ["modifyvm", :id, "--name", "ubuntu-host2"]
    end
  end
  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    # install java runtime environment
    apt-get install -y default-jre
    # install docker
  #  apt-get install -y docker.io
  # usermod -a -G docker vagrant


  # установка rabbitmq
    apt-get install curl gnupg debian-keyring debian-archive-keyring apt-transport-https -y

## Team RabbitMQ's main signing key
    apt-key adv --keyserver "hkps://keys.openpgp.org" --recv-keys "0x0A9AF2115F4687BD29803A206B73A36E6026DFCA"
## Cloudsmith: modern Erlang repository
    curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key | sudo apt-key add -
## Cloudsmith: RabbitMQ repository
    curl -1sLf https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key | sudo apt-key add -

## Add apt repositories maintained by Team RabbitMQ
    sudo tee /etc/apt/sources.list.d/rabbitmq.list <<EOF
## Provides modern Erlang/OTP releases
##
    deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main
    deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu bionic main

## Provides RabbitMQ
##
    deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bionic main
    deb-src https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu bionic main
EOF

## Update package indices
    apt-get update -y

## Install Erlang packages
    apt-get install -y erlang-base \
                        erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
                        erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
                        erlang-runtime-tools erlang-snmp erlang-ssl \
                        erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl

## Install rabbitmq-server and its dependencies
    apt-get install rabbitmq-server -y --fix-missing
  SHELL
end